name: Build Jekyll Site

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [google-sheets-update]

env:
  PAGES_REPO_NWO: EluLolaito/EluLolaito.github.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch CSV from Google Sheets
        run: |
          # mkdir -p ./_data
          curl -L "${{ secrets.CSV_URL }}" -o ./_data/skysheets.csv

      - name: Fetch YML from Google Sheets
        run: |
          pwd
          # ls
          # mkdir -p ./_data
          ls
          curl -L "${{ secrets.YML_URL }}" -o ./_data/songs.yml

      # Step to verify that CSV/YML files were fetched correctly
      - name: Check fetched files
        run: |
          echo "Checking files in _data..."
          ls -l ./_data
          cat ./_data/skysheets.csv || echo "CSV file missing!"
          cat ./_data/songs.yml || echo "YML file missing!"

      - name: Move Data and Link
        run: |
          mkdir -p .jekyll_data
          mv _data/skysheets.csv .jekyll_data/skysheets.csv
          mv _data/songs.yml .jekyll_data/songs.yml
          ln -s $(pwd)/.jekyll_data _data

      - name: Setup Ruby & Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Build Jekyll site and force it to use updated data
      - name: Build Jekyll site
        run: |
          echo "Creating _data folder in the current directory..."
          pwd
          # JEKYLL_ENV=production bundle exec jekyll build --source ./ --verbose
          touch ./_data/skysheets.csv ./_data/songs.yml
          # bundle exec jekyll clean  # Clears any cached build data
          JEKYLL_ENV=production bundle exec jekyll build --verbose

      - name: Debug Jekyll Data
        run: |
          echo "Checking _data folder after build..."
          pwd
          ls
          ls -l ./_data
          # cat ./_data/skysheets.csv
          cat ./_data/songs.yml
          ls ./_site

      - name: Remove _data After Build
        run: rm -rf _data

        # - name: Remove CSV after build
        #   run: rm _data/skysheets.csv

        # - name: Deploy to GitHub Pages
        #   uses: JamesIves/github-pages-deploy-action@v4
        #   with:
        #     branch: gh-pages
        #     folder: _site
